version: '3.8'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./ui/wiki_watch:/app/wiki_watch
    command: ["ng", "serve", "--host", "0.0.0.0"]

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"  # Assuming MySQL default port, adjust if using another DB
    volumes:
      - db_data:/var/lib/mysql  # Persistent data storage

volumes:
  db_data: