# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Set environment variables for the MySQL root password and default database
ENV MYSQL_ROOT_PASSWORD=admin
ENV MYSQL_DATABASE=example

# Copy any SQL scripts or initialization files; optional
# COPY ./your-init-scripts.sql /docker-entrypoint-initdb.d/